import * as React from 'react';
import Box from '@mui/material/Box';
import Toolbar from '@mui/material/Toolbar';
import List from '@mui/material/List';
import CssBaseline from '@mui/material/CssBaseline';
import Typography from '@mui/material/Typography';
import IconButton from '@mui/material/IconButton';
import MenuIcon from '@mui/icons-material/Menu';
import ListItem from '@mui/material/ListItem';
import ListItemButton from '@mui/material/ListItemButton';
import ListItemIcon from '@mui/material/ListItemIcon';
import ListItemText from '@mui/material/ListItemText';
import {AppBar, Drawer} from "./StyledComponents";
import Head from "next/head";
import SellIcon from '@mui/icons-material/Sell';
import HomeIcon from '@mui/icons-material/Home';
import Link from 'next/link';
import {LinearProgress } from '@mui/material';
import {useSelector} from "react-redux";
import {selectLocation} from "@/libs/redux/navBar/useSlice";
import {useRouter} from "next/router";
import {useEffect} from "react";

export interface LayoutProps  {
    children: React.ReactNode,
    title?: string,
    loading?: boolean,
}

export default function Layout(props: LayoutProps) {
    const [open, setOpen] = React.useState(false);
    const router = useRouter();

    const { location } = useSelector(selectLocation)
    useEffect(() => {
        console.log(location)
    }, [location])


    return (
        <>
            <Head>
                <title>{props.title ?? 'GED Demo'}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Box sx={{ display: 'flex' }}>
                <CssBaseline />
                <AppBar position="fixed" open={open} sx={{ zIndex: (theme) => theme.zIndex.drawer + 1 }}>
                    <Toolbar>
                        <IconButton
                            color="inherit"
                            aria-label="open drawer"
                            onClick={() => setOpen(!open)}
                            edge="start"
                            sx={{
                                marginRight: 5,
                            }}
                        >
                        <MenuIcon />
                        </IconButton>
                        <Typography variant="h6" noWrap component="div" sx={{color: (theme) => theme.palette.text.secondary}}>
                            Mini variant drawer
                        </Typography>
                    </Toolbar>
                    {props.loading && <LinearProgress />}

                </AppBar>
                <Drawer variant="permanent" open={open}>
                    <Toolbar />
                    <List>
                        {[
                            {title: 'home', text: 'menu', icon: <HomeIcon/>, link: '/'},
                            {title: 'products', text: 'liste des produits', icon: <SellIcon/>, link: '/products'}
                        ].map((item) => (
                            <Link
                                href={item.link}
                                key={`listItemElement${item.title}`}
                                // className={item.link === router.pathname ? 'sg-question-title' : 'listItemNotSelected'}
                            >
                                <ListItem  key={'home_side_bar'} disablePadding sx={{ display: 'block' }}>
                                    <ListItemButton
                                        sx={{
                                            minHeight: 48,
                                            justifyContent: open ? 'initial' : 'center',
                                            px: 2.5,
                                        }}
                                    >
                                        <ListItemIcon
                                            sx={{
                                                minWidth: 0,
                                                mr: open ? 3 : 'auto',
                                                justifyContent: 'center',
                                            }}
                                        >
                                            {item.icon}
                                        </ListItemIcon>
                                        <ListItemText primary={item.text} sx={{ opacity: open ? 1 : 0 }} />
                                    </ListItemButton>
                                </ListItem>
                            </Link>
                        ))}
                    </List>
                </Drawer>
                <Box component="main" sx={{ flexGrow: 1 }}>
                    <Toolbar />
                    <Box sx={{p: 3}}>
                        {props.children}
                    </Box>
                </Box>
            </Box>
        </>
    );
}
